export const dictionary = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "I", "it", "for", "not", "on", "with", "he", "as", "you", "do", "at", "this", "but", "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what", "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    // Common words in college reviews
    "college", "university", "student", "professor", "class", "course", "lecture", "exam", "study", "campus", "dormitory", "library", "cafeteria", "academic", "faculty", "research", "degree", "major", "minor", "semester", "curriculum", "tuition", "scholarship", "internship", "alumni", "graduate", "undergraduate",
    "enrollment", "module", "credit", "syllabus", "thesis", "dissertation", "fellowship", "department", "administration", "registrar", "enroll", "dropout", "transfer", "advisor", "counselor", "extracurricular", "club", "organization", "society", "team", "athlete", "coach", "financial aid", "grant", "loan", "bursary", "campus life", "student life",
    "housing", "accommodation", "roommate", "application", "admission", "applicant", "acceptance", "rejection", "matriculate", "orientation", "convocation", "commencement", "graduation", "freshman", "sophomore", "junior", "senior", "peer", "colleague", "mentor", "tutor", "lecture hall", "workshop", "seminar", "conference", "forum", "discussion",
    "networking", "career", "job", "employment", "recruitment", "interview", "resume", "CV", "cover letter", "intern", "placement", "practicum", "exchange", "abroad", "international", "global", "program", "distance learning", "online course", "e-learning", "virtual", "hybrid", "technology", "software", "platform", "system", "accessibility", "support",
    "wellness", "health", "counseling", "service", "volunteer", "community", "involvement", "sustainability", "green", "environment", "campus safety", "security", "policy", "compliance", "regulation", "accreditation", "standard", "quality", "assessment", "evaluation", "review", "feedback", "rating", "ranking", "performance", "achievement", "success"
  ];
  